name = "ObjectStores"
uuid = "e102f8c2-d0e1-11e8-0211-39155c3f0463"
authors = ["Jock Lawrie <jock.lawrie@gmail.com>"]
version = "0.2.0"

[deps]
Authorization = "edb23f2a-d586-11e8-2b8a-1bcdb9b1bfed"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
